Owning wrapper with iterator interface
RnDome/bwapi-c pull request #11
Opened 2017-05-09 10:44 UTC by 0x7CFE

May be used to efficiently wrap containers
received from BWAPI such as Unitset.

Move semantics allow us to store container data
inside the iterator without copying the contents.

2017-05-09 12:34 UTC, kpp commented on include/Iterator.h
> +#ifdef __cplusplus
вот это всё надо спрятать в cpp файл. Смотри на String

2017-05-09 12:36 UTC, kpp commented on src/Iterator.cpp
> +    assert(self);
тут не надо проверку

2017-05-09 12:36 UTC, kpp commented on src/Iterator.cpp
> +    assert(self);
тут не надо проверку

2017-05-11 08:07 UTC, 0x7CFE commented on src/Iterator.cpp
> +    assert(self);
С какой стати не надо? Это sanity check.

2017-05-11 15:44 UTC, kpp commented on src/IteratorImpl.h
> +#pragma once
Should be IteratorImpl.hpp . But do we really have to include it from somewhere? You may put this code inside .cpp

2017-05-11 19:30 UTC, kpp requested changes
+ add example for any function returning sets

2017-05-11 19:30 UTC, kpp commented on src/IteratorImpl.h
> +};
We need more types

2017-05-11 19:30 UTC, kpp commented on src/IteratorImpl.h
> +    // May be used for runtime checks
can be used*

2017-05-12 16:12 UTC, kpp requested changes

2017-05-12 16:12 UTC, kpp commented on src/IteratorImpl.h
> +    static_assert(type != itUnknown, "Out must be a known container type");
уже не надо

2017-05-12 16:12 UTC, kpp commented on src/Unit.cpp
> +#include "IteratorImpl.h"
.hpp

2017-05-12 17:16 UTC, kpp approved these changes

2017-05-12 17:33 UTC, kpp commented
Дим, а сделаешь from_iter? Из итератора в Unitset?

2017-05-13 09:38 UTC, 0x7CFE commented
Rebased and squashed commits, added implementation for trivial `Unit`'s methods, returning `Unitset`.

2017-05-13 11:17 UTC, merged