Borrowing iterator and fixes
RnDome/bwapi-c pull request #23
Opened 2017-05-13 19:25 UTC by 0x7CFE

2017-05-13 19:56 UTC, kpp requested changes

2017-05-13 19:56 UTC, kpp commented on src/Unit.cpp
> +    const auto&& units = reinterpret_cast<BWAPI::UnitInterface*>(self)->getLoadedUnits();
Либо `auto&&`, либо `const auto&`

2017-05-13 19:56 UTC, kpp commented on src/Unit.cpp
> +    const auto&& interceptors = reinterpret_cast<BWAPI::UnitInterface*>(self)->getInterceptors();
Почему `UnitInterface*`, а не `Unit`?

2017-05-13 19:56 UTC, kpp commented on src/Unit.cpp
> +    const auto&& larva = reinterpret_cast<BWAPI::UnitInterface*>(self)->getLarva();
`return into_iter<UnitIterator>(std::move(larva))`

2017-05-13 19:56 UTC, kpp commented on src/IteratorImpl.hpp
> +        : container(std::move(container)), iter(container.begin())
аргумент лучше назвать `Container container_`, чтобы не было шадовинга, и iter был проинициализирован от члена класса, а не от уже смувленного аргумента

2017-05-13 19:56 UTC, kpp commented on src/Game.cpp
> +    return as_iter<RegionIterator>(regions);
И тут заканчивается область видимости, regions дохнет, RegionIterator ссылается на мертвую ссылку

2017-05-13 19:58 UTC, kpp commented on src/Game.cpp
> +    return as_iter<RegionIterator>(regions);
```
==8202== Use of uninitialised value of size 8
==8202==    at 0x4F3BB61: ??? (in /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.21)
==8202==    by 0x4F3D1BB: std::ostreambuf_iterator<char, std::char_traits<char> > std::num_put<char, std::ostreambuf_iterator<char, std::char_traits<char> > >::_M_insert_int<unsigned long>(std::ostreambuf_iterator<char, std::char_traits<char> >, std::ios_base&, char, unsigned long) const (in /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.21)
==8202==    by 0x4F3D3AE: std::num_put<char, std::ostreambuf_iterator<char, std::char_traits<char> > >::do_put(std::ostreambuf_iterator<char, std::char_traits<char> >, std::ios_base&, char, void const*) const (in /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.21)
==8202==    by 0x4F4A449: std::ostream& std::ostream::_M_insert<void const*>(void const*) (in /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.21)
==8202==    by 0x400BB7: main (test.cpp:34)
```

2017-05-13 22:00 UTC, kpp commented on src/IteratorImpl.hpp
> +    BorrowingIterator(const Container& container)
Надо запретить конструктор по значению, наверное

2017-05-14 07:13 UTC, 0x7CFE commented on src/IteratorImpl.hpp
> +    BorrowingIterator(const Container& container)
Нельзя. Если его определить, но полезут ошибки компиляции потому что вызов конструктора неоднозначный.

2017-05-14 08:11 UTC, kpp approved these changes

2017-05-14 09:05 UTC, merged

2017-05-14 13:29 UTC, kpp commented
```
src/Force.cpp:    return into_iter<PlayerIterator>(std::move(players));
src/IteratorImpl.hpp:Out* into_iter(Container container) {
src/Player.cpp:    return into_iter<UnitIterator>(units);
src/Region.cpp:    return into_iter<RegionIterator>(regions);
src/Unit.cpp:    return into_iter<UnitIterator>(std::move(units));
src/Unit.cpp:    return into_iter<UnitIterator>(std::move(interceptors));
src/Unit.cpp:    return into_iter<UnitIterator>(std::move(larva));
```