Move semantics in String implementation, safe_cast<>, etc
RnDome/bwapi-c pull request #8
Opened 2017-05-09 10:04 UTC by 0x7CFE

2017-05-09 10:15 UTC, kpp commented on src/Player.cpp
> +#include <Types.h>
Не надо

2017-05-09 12:40 UTC, kpp requested changes

2017-05-09 12:40 UTC, kpp commented on src/String.cpp
> +    assert(self);
тут проверка не нужна

2017-05-09 14:10 UTC, 0x7CFE commented on src/String.cpp
> +    assert(self);
Семантика этой проверки не в том, что «delete надо вызывать на ненулевом указателе», а в том, что по логике программы сюда должны передать ненулевой указатель. Если он нулевой, что-то сильно не так в вызывающем коде.

2017-05-09 16:00 UTC, kpp commented on src/String.cpp
> +    assert(self);
ну ок

2017-05-11 16:10 UTC, kpp approved these changes

2017-05-28 14:39 UTC, merged